[Eth]
NetworkId = 212121
StateScheme = "hash"


[peers.connection_info]
# The maximum number of outbound peers (peers we connect to)
max_outbound = 5
# The maximum number of inbound peers (peers that connect to us)
max_inbound = 30

