name: Rust
on:
  pull_request:
    # No branches specified, will trigger on all pull request events

permissions:
  contents: write
  deployments: write

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-C target-cpu=native"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - uses: olix0r/cargo-action-fmt/setup@v2

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Check Formatting
        run: cargo fmt --all -- --check

      - name: Lint src
        run: cargo clippy --message-format=json -- -D warnings | cargo-action-fmt

      - name: Lint tests
        run: cargo clippy --tests --message-format=json -- -D warnings | cargo-action-fmt

      - name: Build & Test
        run: |
          cargo build --release
        #   cargo test --release --no-fail-fast --verbose -- --nocapture
